export enum SeasonType {
  Regular = 1,
  Preseason = 2,
  Postseason = 3,
}

export enum Conference {
  NFC = 7,
  AFC = 8,
}

export enum TeamId {
  FALCONS = 1,
  BILLS = 2,
  BEARS = 3,
  BENGALS = 4,
  BROWNS = 5,
  COWBOYS = 6,
  BRONCOS = 7,
  LIONS = 8,
  PACKERS = 9,
  TITANS = 10,
  COLTS = 11,
  CHIEFS = 12,
  RAIDERS = 13,
  RAMS = 14,
  DOLPHINS = 15,
  VIKINGS = 16,
  PATRIOTS = 17,
  SAINTS = 18,
  GIANTS = 19,
  JETS = 20,
  EAGLES = 21,
  CARDINALS = 22,
  STEELERS = 23,
  CHARGERS = 24,
  "49ERS" = 25,
  SEAHAWKS = 26,
  BUCCANEERS = 27,
  COMMANDERS = 28,
  PANTHERS = 29,
  JAGUARS = 30,
  RAVENS = 33,
  TEXANS = 34,
}
